config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get '/posts/:id/share', to:'posts#share',as: :share
  resources :posts,except: [:index]
  resources :pages,param: :nickname
  get '/confirm/:id', to: 'posts#confirm', as: :confirm
  get '/posts/:id/element', to:'posts#element',as: :element
  get '/agreement',to:'pages#agreement'
  get '/about',to: 'pages#about'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  devise_scope :user do
    delete '/users/:id' => 'users/registrations#destroy'
  end
end

app/views/pages/about.html.erb
<h3>懺悔メーカーとは</h3><br>
<h4>①誰しもが抱えうる些細な罪</h4>
<%= image_tag 'intro1.png', width: '315',class: 'intro-image' %><br>
<p>などを・・</p><br>
<h4>②画像付きツイートで懺悔！</h4>
<%= image_tag 'intro2.png', width: '315',class: 'intro-image' %><br>
<p>なんと、<span class='under'>ただそれだけのサービスです。</span></p><br>
<p>が・・・</p>
<h4>③フォロワーから許しが得られるかもしれません</h4>
<%= image_tag 'intro3.png', width: '315',class: 'intro-image' %><br>
<p>「汝の罪を許す」が押されると、@ツイートでリアクションがきます</p>

app/views/pages/index.html.erb
<%= link_to " Twitterでログイン/登録", user_twitter_omniauth_authorize_path,class: "btn btn-primary my-4 py-2 fa fa-twitter twitterlogin" %>

<h3>懺悔メーカーとは</h3><br>
<h4>①誰しもが抱えうる些細な罪</h4>
<p>例えば・・・</p>
<%= image_tag 'intro1.png', width: '315',class: 'intro-image' %><br>
<p>などを</p><br>
<h4>②画像付きツイートで懺悔！</h4>
<%= image_tag 'intro2.png', width: '315',class: 'intro-image' %><br>
<p>胸に秘めたままの罪を告白する</p>
<p>なんと、<span class='under'>ただそれだけのサービスなのです！</span></p><br>

<p>が、もしかすると・・・</p>
<h4>③フォロワーから許しが得られるかもしれません</h4>
<%= image_tag 'intro3.png', width: '315',class: 'intro-image' %><br>
<p>(「汝の罪を許します」が押されると、@ツイートでリアクションがきます)</p>

<br>

<p>▼罪を告白して、罪悪感を減らしましょう！▼</p>
<%= link_to " Twitterでログイン/登録", user_twitter_omniauth_authorize_path,class: "btn btn-primary my-4 py-2 fa fa-twitter twitterlogin" %>
<p>※勝手にツイートされることはありません</p>

<br>
<br>
<br>
<p>▽SNSでシェア▽</p>
<a href="https://twitter.com/share?url=https://www.zangemaker.com&hashtags=懺悔メーカー" target="_blank" class="btn btn-info btn-sm" data-show-count="false">Twitter</a>
<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.zangemaker.com" target="_blank" class="btn btn-info btn-sm" data-show-count="false">Facebook</a>
<a href="http://line.me/R/msg/text/?http://www.zangemaker.com" target="_blank" class="btn btn-info btn-sm" data-show-count="false">LINE</a>

app/views/pages/show.html.erb
<img src= <%= current_user.image %> class="icon"><br>
<span><%= current_user.name %>の懺悔</span><br>

<br><%= link_to "罪を告白する",new_post_url,class: "btn btn-info btn-lg my-3 px-5 py-2 confession" %>

<div class="container-fluid text-center">
<div class="row">
<div class="col-md-3"></div>

<div class='past-content col-md-6'>

<span>過去の懺悔一覧</span>
<% @posts.each do |post| %>
<div class='list-content'>
  <%= image_tag post.picture, width: '200',class: 'image_past' %>
  <span><%= link_to '投稿を削除',post_path(post),method: :delete,data:{confirm: '削除しますか？'},class: 'delete-confirm text-muted' %></span>
</div>
<% end %>

</div>

<div class="col-md-3"></div>
</div>
</div>

<br><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "btn btn-primary my-4 py-2 fa fa-twitter" %>